In [1]:
import numpy as np

In [2]:
array_int = np.array([1, 2, 3])
array_int

array([1, 2, 3])

In [4]:
array_float = array_int.astype('float64')
array_float

array([1., 2., 3.])

In [5]:
array_float.dtype

dtype('float64')

In [6]:
array_int.dtype

dtype('int32')

In [9]:
array1 = np.arange(1, 10, 1)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Fancy Indexing

In [13]:
array1d = np.arange(1, 10, 1)
array2d = array1d.reshape(3, 3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
array2d[[0, 1], 2]

array([3, 6])

In [15]:
array2d[[0, 1]]

array([[1, 2, 3],
       [4, 5, 6]])

## Boolean Indexing

In [19]:
array1d[array1d > 5]

array([6, 7, 8, 9])

In [20]:
boolean_index = array1d > 5
array1d[boolean_index]

array([6, 7, 8, 9])

## Sort && Argsort

In [21]:
array = np.array([3, 1, 9, 5])

In [22]:
sort_array = np.sort(array)
sort_array

array([1, 3, 5, 9])

In [23]:
sort_inverse_array = np.sort(array)[::-1]
sort_inverse_array

array([9, 5, 3, 1])

In [26]:
tmp = array.sort()
print(tmp)
print(array)

None
[1 3 5 9]


In [27]:
array[::-1]

array([9, 5, 3, 1])

In [28]:
array2d = np.array([[3, 4], [7, 1]])
array2d

array([[3, 4],
       [7, 1]])

In [29]:
np.sort(array2d, axis=0)

array([[3, 1],
       [7, 4]])

In [30]:
np.sort(array2d, axis=1)

array([[3, 4],
       [1, 7]])

In [33]:
array = np.array([3, 5, 1, 9])
array

array([3, 5, 1, 9])

In [34]:
np.argsort(array)

array([2, 0, 1, 3], dtype=int64)